Buckitup-chat/chat

lib/chat_web/live/main_live/index.html.heex
lib/chat_web/live/main_live/layout/message.ex

https://user-images.githubusercontent.com/90610934/211955992-d30b5715-7062-4025-b7b2-015fe7b89f97.mov

Invite messages should be auto-edited upon accepting

---

lib/chat_web/live/main_live/layout/message.ex

Show name and size for media files

---

assets/js/hooks/chat.js
lib/chat_web/live/main_live/index.html.heex
lib/chat_web/live/main_live/layout/chat.ex

Load more messages immediately and on scroll

---

lib/chat/utils.ex

fix full hash usage

---

lib/chat/rooms.ex
lib/chat_web/live/main_live/page/lobby.ex
lib/chat_web/live/main_live/page/room.ex
test/chat/actor_test.exs
test/chat/log_test.exs
test/chat/ordering_test.exs
test/chat/room_test.exs
test/chat/rooms/private_room_test.exs
test/chat/rooms/request_room_test.exs

db unleash: room creation do not wait for DB

---

assets/js/app.js
lib/chat_web/live/main_live/index.html.heex
lib/chat_web/live/main_live/layout/image_gallery.ex
lib/chat_web/live/main_live/layout/message.ex
lib/chat_web/live/main_live/page/dialog.ex
lib/chat_web/live/main_live/page/dialog_router.ex
lib/chat_web/live/main_live/page/room.ex
lib/chat_web/live/main_live/page/room_router.ex

ref -> https://github.com/Buckitup-chat/chat/issues/82
To read -> https://stackoverflow.com/a/73764437

Optimize gallery image preloads

---

lib/chat/dialogs.ex
lib/chat_web/live/main_live/layout/message.ex
lib/chat_web/live/main_live/page/dialog.ex
lib/chat_web/live/main_live/page/lobby.ex

store room key copy to My notes

---

assets/css/app.css
lib/chat_web/live/main_live/index.html.heex

https://user-images.githubusercontent.com/90610934/218836102-942345cc-1001-43ca-a55b-d7870f8939c2.mov

logout without the keys message

---

lib/chat_web/live/main_live/layout/uploader.ex

https://user-images.githubusercontent.com/104422464/219621987-8e8a2edd-9ef5-4826-b2fb-d1fb30c42c7a.mp4

video, images uploads work from gallery

---

lib/chat_web/live/main_live/index.html.heex
lib/chat_web/live/main_live/layout/message.ex
lib/chat_web/live/main_live/page/dialog.ex

refs: 
- https://github.com/Buckitup-chat/chat/issues/189
- https://github.com/Buckitup-chat/chat/issues/188
- https://github.com/Buckitup-chat/chat/issues/185
- https://github.com/Buckitup-chat/chat/issues/184

fix room invites

---

CHANGELOG.md
lib/chat/log.ex

lost feed names

---

CHANGELOG.md
lib/chat/db/backup_db_supervisor.ex

Required for https://github.com/Buckitup-chat/platform/pull/5.

Enable setting backup DB name

---

CHANGELOG.md
lib/chat_web/live/main_live/layout/message_input.ex

Changed onkeydown event to submit edited message

Fix of submitting edited  message by Enter

---

CHANGELOG.md
lib/chat_web/live/main_live/layout/message.ex

fix broken image render

---

CHANGELOG.md
lib/chat/file_fs.ex

copying fix

---

CHANGELOG.md
lib/chat/application.ex
lib/chat/db/free_spaces.ex
lib/chat/db/free_spaces_poller.ex
lib/chat_web/live/main_live/index.ex
lib/chat_web/live/main_live/index.html.heex
lib/chat_web/live/main_live/layout/admin.ex
lib/chat_web/live/main_live/page/admin_panel.ex

According to #167.
Add free spaces for Internal DB, Main DB, Media DB (Cargo DB, Backup DB, or Onliners DB) on admin panel every 2 seconds by FreeSpacesPoller.

feat: free spaces on admin panel

---

lib/chat_web/live/main_live/layout/room.ex

Change order of mobile menu elements in room

fix: to long buttons on mobile

---

CHANGELOG.md
lib/chat/chunked_files.ex
lib/chat/chunked_files_broker.ex
lib/chat_web/live/helpers/uploader.ex

refs: 
- https://github.com/Buckitup-chat/chat/issues/411
- https://github.com/Buckitup-chat/chat/issues/341

411: half-uploaded files bugfix

---

CHANGELOG.md
assets/js/upchunk_upload.js
lib/chat_web/live/helpers/uploader.ex
lib/chat_web/live/main_live/layout/uploader.ex

https://github.com/Buckitup-chat/chat/assets/90610934/2c19c24d-9b0b-4e8a-ab4b-15326b2de342

426: improved pause handling

---

CHANGELOG.md
lib/chat/file_fs/dir2.ex
lib/chat/file_fs/dir3.ex

456: has_file waits for full size chunk

---

CHANGELOG.md
lib/chat/sync/cargo_scenario.livemd
lib/chat_web/live/main_live/index.html.heex
lib/chat_web/live/main_live/page/recover_key_share.ex

solution ref: https://github.com/Buckitup-chat/platform/pull/67

469: drive indication docs update

---

CHANGELOG.md

495: complete cargo room after scenario finished

---

CHANGELOG.md
lib/chat_web/live/helpers/shared.ex

512: fix Chat.TaskSupervisor usage

---

CHANGELOG.md
lib/chat_web/live/main_live/index.html.heex

492: cargo opens room on mobile

---

.github/workflows/elixir.yml
CHANGELOG.md
elixir_buildpack.config
lib/chat_web/live/main_live/admin/camera_preview.ex
lib/chat_web/live/main_live/admin/cargo_camera_sensors_form.ex

532: async camera preview

---

CHANGELOG.md
lib/chat/db/scope/invitation_level.ex
lib/chat/db/scope/key_scope.ex
test/chat/db/scope/cargo_key_scope_test.exs

Fix cargo sync invitations processing

fix: cargo sync

---

CHANGELOG.md
lib/chat/db/pipeline/writer_process.ex

590: skip when demand takes too long

---

CHANGELOG.md
lib/chat_web/live/main_live/layout/message.ex

578: fix message selection

---

CHANGELOG.md
lib/chat_web/live/live_helpers.ex

563: fix sidebar disappear

---

CHANGELOG.md

603: reset indication when decided not cargo

---

CHANGELOG.md
lib/chat/card.ex
lib/chat/db/scope/invitation_level.ex
lib/chat/rooms/room_request.ex
test/chat/network_synchronization/peer_detection/detector_test.exs
test/chat/sync/cargo_operator_and_sensor_flow_test.exs
test/support/db/sync.ex
test/support/isolated_data_case.ex

611 cargo sync fix

---

CHANGELOG.md
lib/chat_web/live/main_live/page/image_gallery.ex

621 gallery shows image loading

---

CHANGELOG.md
lib/chat/db/scope/key_scope.ex
lib/chat/db_structures.livemd
lib/chat/dialogs.ex
lib/chat/room_invite_index.ex
lib/chat_web/live/main_live/index.ex
lib/chat_web/live/main_live/page/admin_panel.ex
lib/chat_web/live/main_live/page/room.ex
test/chat/db/scope/cargo_key_scope_on_isolated_test.exs
test/chat/db/scope/cargo_key_scope_test.exs
test/chat/db/scope/key_scope_test.exs
test/chat/sync/cargo_operator_and_sensor_flow_test.exs
test/chat_web/live/main_live/index_test.exs
test/naive_api/network_sync_test.exs

619 decrease cargo scope

---

lib/chat/db/scope/key_scope.ex

619: skip old invites for cargo

---

CHANGELOG.md
lib/chat/db/scope/key_scope.ex

630: handle invite dialogs

---

assets/js/EncryptionManager.js

vault: idb switch
